# Generated by Django 4.1.2 on 2024-06-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique_noemi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('completada', 'Completada')], default='en_proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
